---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Output tables

In this section we present all table outputs that were used to generate the information and plots in the results section.  

```{r, include=FALSE}
dstPath <- file.path("tables")
```

```{r tables, results = "asis"}
listOfTables <- list("Table 1" = data.frame(read.csv(file.path(dstPath, "anovaLmCovariates.csv")))[,-1],
                     "Table 2" = data.frame(read.csv(file.path(dstPath, "habitatDT.csv")))[,-1],
                     "Table 3" = data.frame(read.csv(file.path(dstPath, "meanHabitatDT.csv")))[,-1],
                     "Table 4" = data.frame(read.csv(file.path(dstPath, "speciesDT.csv")))[,-1],
                     "Table 5" = data.frame(read.csv(file.path(dstPath, "meanSpeciesDT.csv")))[,-1],
                     "Table 6" = data.frame(read.csv(file.path(dstPath, "throughTimeTableGroupsD.csv")))[,-1],
                     "Table 7" = data.frame(read.csv(file.path(dstPath, "throughTimeTableSD.csv")))[,-1])

listOfCaptions <- list(
  "Table 1" = "This table represents a linear model fitted with all data available to identify which covariates influence the calculation of BCUI results.",
  "Table 2" = "This table is a statistical summary of all data for each habitat group per scenario.",
  "Table 3" = "This table is a statistical summary of all data for habitat group across all scenarios.",
  "Table 4" = "This table is a statistical summary of all data for each species per scenario.",
  "Table 5" = "This table is a statistical summary of all data for individual species across all scenarios.",
  "Table 6" = "This table presents the trend through time for each habitat group per scenario.",
  "Table 7" = "This table presents the trend through time for each species per scenario."
)

for (i in names(listOfTables)) {
  cat("\n\n")
  cat("##", i, "\n\n") # Create second level headings with the names.
  
  cat(listOfCaptions[[i]])
    
  cat(knitr::knit_print(shiny::tags$br()))
  
  opts <- list(
      scrollX = TRUE,
      autoWidth = TRUE,
      columnDefs = list(list(width = "200px", targets = c(1, 3)))
  )
  
  #colIsNumeric <- names(vapply(listOfTables[[i]], is, logical(1), class2 = "numeric"))
  
  cat(
    #shiny::tagList(
    knitr::knit_print(
      DT::datatable(listOfTables[[i]], options = opts, height = "auto", width = "100%")
      ## TODO: round to 3 decimal places:
      ##   NOTE: neither `DT::formatRound(columns = 1:ncol(listOfTables[[i]]), digits = 3)` nor
      ##   `DT::formatRound(columns = colIsNumeric, digits = 3)` seem to work as they mask any
      ##   non-numeric values and also mess up column alignment for tables with <10 rows
    )
  )
}
```
